import "../globals.css";
import Link from "next/link";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "100",
});

export const metadata: Metadata = {
  title: "My Awesome Site",
  description: "Generated by Next + Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto} max-w-3xl mx-auto py-10`}>
        <header>
          <Link
            href="/"
            className="bg-gradient-to-r from-orange-400 via-red-400 to-violet-600 bg-clip-text text-transparent text-lg font-bold"
          >
            Jawdat
          </Link>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
